### ISSUE TITLE
LabTop Mk IV - Modify Verb Table so that quirk isn't required

### ISSUE THREAD

**Issue by Sean-StarLabs** [StarLabsLtd/firmware#1]

**Comment by Sean-StarLabs** [comment]
Resolved with cff69d09ac466ac346a0795ac2f1aacfe94e5279

**Comment by tjheslin1** [comment]
Sounds like this was resolved. Should this be closed?

**Comment by Sean-StarLabs** [comment]
It was resolved but I'm working on an update that removes the need for the quirk

**Comment by Sean-StarLabs** [comment]
Resolved with fc568a6c3595114dcd40fa254121093b8eb422e0
