### ISSUE TITLE
[Starbook MkVI - Intel] Coreboot 8.38, coreboot CMOS checksum is bad

### ISSUE THREAD

**Issue by divico** [StarLabsLtd/firmware#100]
I installed coreboot `8.38` in lvfs-testing using fwupd as usual. When running `coreboot-configurator` there is the error message
`nvramtool: Warning: coreboot CMOS checksum is bad. Computed checksum: 0x33c. Stored checksum: 0x3f`

```
pacman -Q coreboot-configurator
coreboot-configurator 9-2
```

```
nvramtool -v
This is nvramtool version 2.1.
```

**Comment by Sean-StarLabs** [comment]
Already fixed, ready for `8.40` but you can correct it with a write, i.e. `sudo nvramtool -w fn_ctrl_swap=Disable`.
