### ISSUE TITLE
[Starbook MkVI -Intel][Coreboot] - Charge via USB?

### ISSUE THREAD

**Issue by donnekgit** [StarLabsLtd/firmware#107]
Just wondering if it's possible to charge via the USB port.  I'm asking because charging with the barrel charger seems to be playing up a bit.  The socket on the laptop seems a bit loose, and sometimes when plugged in the charger will not start charging for a while, and seems to need a jiggle on the plug for it to work.  So just thinking about a Plan B.

**Comment by Sean-StarLabs** [comment]
You can via USB-C PD.

Is your EC up-to-date? There were some improvements to the DC charging the later versions

**Comment by donnekgit** [comment]
Oh, great, so that's an option.

I'll check the EC.

**Comment by donnekgit** [comment]
Sorry, have to reopen.  Got a Ugreen 65W charger, and plugging it in gives what seems to be the same behaviour as in https://github.com/StarLabsLtd/firmware/issues/95 (it goes on/of, on/off).  So I'm assuming the EC needs updating (the current one is 1.12?).

However, how do I access this?  I take it you have to boot into the UEFI shell, but then what do I do?  The other issue refers to running ectool - is that in the shell already, or do I need to install it?

**Comment by Sean-StarLabs** [comment]
https://support.starlabs.systems/kb/firmware/getting-started

Any questions, just ping support :)
