### ISSUE TITLE
Error when opening coreboot-configurator

### ISSUE THREAD

**Issue by barbastrejo12** [StarLabsLtd/firmware#110]
Just upgraded a labtop mkIII running debian bookworm to 8.50, and soon after trying to open coreboot configurator got this error:
![Schermata del 2023-06-21 14-37-49](https://github.com/StarLabsLtd/firmware/assets/130546147/d2f4b6e2-c55f-4f1a-81eb-744d542a37ac)

**Comment by Sean-StarLabs** [comment]
That's right - coreboot-configurator isn't needed any more

**Comment by barbastrejo12** [comment]
Fantastic, jsut rebooted and got inside it, I was dreaming about that! Thank you all for the great work, it got so beautiful with those functions without needing coreboot-configurator. Very elegant!
