### ISSUE TITLE
Labtop mkIII doesn't resume from sleep when I close the lid

### ISSUE THREAD

**Issue by barbastrejo12** [StarLabsLtd/firmware#112]
Have been seeing this behavior after upgrade to 8.50. I close the lid. If I let the lid open it resumes. Sometimes it works, sometimes it does not.

**Comment by barbastrejo12** [comment]
Had a strange behavior yesterday, the L3 had % battery, I plug the USb-C charging cable it turns off, I try to turn it on many times for 1hour, no sign of life, red led on. I unplug the cable, leave alone for around 30minutes, press power and it starts at 47% battery.

**Comment by Sean-StarLabs** [comment]
`8.60` is going up today, which'll fix a couple of things. You are flashing these with an unsupported method, before they even hit the testing remote - so you'll likely find bugs ;)

**Comment by barbastrejo12** [comment]
Thanks for the info Sean. Supported method is fwupd?

**Comment by Sean-StarLabs** [comment]
Yup, that's right - it does clever stuff to get the CMOS in the right state, and that's where things like the backlight state and suspend info is stored.
