### ISSUE TITLE
[Starbook MkVI - Intel][coreboot] S3 not entered when closing lid

### ISSUE THREAD

**Issue by mysfitt** [StarLabsLtd/firmware#114]
I'm not certain if these two things are related, but I have a hunch that they might be. I occasionally have an issue with my Starbook Mk VI not entering S3 sleep when I close the lid. And when opening the Lid and checking kernel messages, I see `ACPI: button: The lid device is not compliant to SW_LID`. Also, on each boot, right before cores 9 - 15 are enabled, I see some other ACPI warnings that could be related to interrupts. Since the message repeats 8 times, I'm guessing these correlate to the atom cores.

> Jul 13 22:20:02 kernel: ACPI: x2apic entry ignored
Jul 13 22:20:02 kernel: ACPI: x2apic entry ignored
Jul 13 22:20:02 kernel: ACPI: x2apic entry ignored
Jul 13 22:20:02 kernel: ACPI: x2apic entry ignored
Jul 13 22:20:02 kernel: ACPI: x2apic entry ignored
Jul 13 22:20:02 kernel: ACPI: x2apic entry ignored
Jul 13 22:20:02 kernel: ACPI: x2apic entry ignored
Jul 13 22:20:02 kernel: ACPI: x2apic entry ignored
Jul 13 22:20:02 kernel:   #9 #10 #11 #12 #13 #14 #15

For reference, I'm currently on 8.40 coreboot and 1.13 ITE.

**Comment by Sean-StarLabs** [comment]
Not related - EC uses a mutex to write; that just makes it more resilient and won't interfere with S3.

If the lid switch is being registered, then it's something software related. Snaps are very good at blocking S3 if you've got any of those installed. If not, the first step would be to figure out what's running when it doesn't enter. Feel free to ping support@starlabs.systems if you can't find it
