### ISSUE TITLE
Keyboard backlight stopped working

### ISSUE THREAD

**Issue by barbastrejo12** [StarLabsLtd/firmware#115]
Hello, the keyboard backlight stopped working on my L3, already tried many things as suggested in the arch's forum:
https://bbs.archlinux.org/viewtopic.php?pid=2110548#p2110548
Could it be something on the coreboot?
Running 8.50

**Comment by Sean-StarLabs** [comment]
`8.60` is going up today, which'll fix a couple of things. You are flashing these with an unsupported method, before they even hit the testing remote - so you'll likely find bugs ;)
