### ISSUE TITLE
[Starbook MkVI - Intel][coreboot] coreboot built without CONFIG_USE_OPTION_TABLE

### ISSUE THREAD

**Issue by divico** [StarLabsLtd/firmware#117]
Running `coreboot-configurator` with coreboot `8.51` and `8.60` fails with the error

`nvramtool: CMOS option table not found in coreboot table.  Apparently, the coreboot installed on this system was built without selecting CONFIG_USE_OPTION_TABLE.`

```
sudo pacman -Q coreboot-configurator
coreboot-configurator 11-1
```
```
nvramtool -v
This is nvramtool version 2.1.
```

Also reported here
https://github.com/StarLabsLtd/firmware/issues/96#issuecomment-1637065240

**Comment by Sean-StarLabs** [comment]
You don't need it anymore, options are in the boot menu
