### ISSUE TITLE
StarBook mkVI Intel - change boot order hangs

### ISSUE THREAD

**Issue by R-VdP** [StarLabsLtd/firmware#118]
When trying to change the boot order in the coreboot firmware interface, the interface hangs when I try to open the page.
All other settings seem to work, but I cannot change the boot order.

I just updated from 8.50 to 8.60.

**Comment by Sean-StarLabs** [comment]
Do you mean Maintenance Manager > Boot options > Change Boot Order?  I can't replicate it - might be a dodgey EFI loader, can you post the output of?
```ls -R /boot/efi/```

**Comment by Sean-StarLabs** [comment]
Assuming solved as no response
