### ISSUE TITLE
[StarBook Mk V] Doesn't boot without charger

### ISSUE THREAD

**Issue by danth** [StarLabsLtd/firmware#120]
Hi! I recently updated coreboot from 8.15 to 8.60 and now the laptop will only boot while the charger is connected. It then continues running as normal with or without the charger.

**Comment by Sean-StarLabs** [comment]
Is that with EC 1.14?

**Comment by danth** [comment]
That's correct.

**Comment by Sean-StarLabs** [comment]
`8.61` fixes and on it's way to the LVFS, takes 1-2 days to make it to testing

**Comment by Sean-StarLabs** [comment]
Ended up at `8.70` but that's now in testing. I'll mark resolved, as I could replicate - but lemme know if not
