### ISSUE TITLE
[StarBook MkV] Battery drain while powered off

### ISSUE THREAD

**Issue by danth** [StarLabsLtd/firmware#123]
Hi again - Although the issue with the LEDs was fixed in 8.80, it seems like the battery is still losing charge while the laptop is powered off, as if something hasn't been shut down fully. Obviously any battery would lose charge over time but this is much faster than usual, as it dies completely in just a few days.

**Comment by Sean-StarLabs** [comment]
It was the power latch, fixed in `8.90`

**Comment by macmpi** [comment]
Does same on LabTop MKIV by the way :wink:

**Comment by macmpi** [comment]
@Sean-StarLabs ok, thanks: opened another issue https://github.com/StarLabsLtd/firmware/issues/124

**Comment by Sean-StarLabs** [comment]
Fixed in `8.94` which is now stable
