### ISSUE TITLE
Keyboard backlight stopped working

### ISSUE THREAD

**Issue by BrtSak** [StarLabsLtd/firmware#125]
Hi,

The keyboard backlight on Labtop MKIV stopped working with firmware 8.50. Upgraded to 8.60 but the issue persists.
It works on version 8.20.

**Comment by Sean-StarLabs** [comment]
`8.94` fixes, it's on its way to stable

**Comment by Sean-StarLabs** [comment]
Now stable

**Comment by BrtSak** [comment]
8.94 didn't fix the keyboard issue. Every release with the "integrated" coreboot configurator has the keyboard backlight broken on Labtop mkiv.

**Comment by Sean-StarLabs** [comment]
* 8.96 :)

**Comment by BrtSak** [comment]
8.96 fixed this issue. Thank You. :)
