### ISSUE TITLE
[All Models] Batteries sometimes aren't initialised

### ISSUE THREAD

**Issue by kevinkbush** [StarLabsLtd/firmware#127]
After installing firmware 8.94 the kernel no longer recognized the battery.  The laptop boots fine but the kernel registers the power source as AC instead of a battery. Downgraded to 8.50.

**Comment by Sean-StarLabs** [comment]
Fixed in EC 1.18, which is included in coreboot 8.95

**Comment by kevinkbush** [comment]
@Sean-StarLabs When will 8.95 be available via fwupdmgr?

**Comment by kevinkbush** [comment]
> @Sean-StarLabs When will 8.95 be available via fwupdmgr?

Nvm, it was there today.  Thanks!
