### ISSUE TITLE
[StarBook MkVI - AMD]  Closing lid while asleep and charging causes system to wake up on v1.12

### ISSUE THREAD

**Issue by tsmithe** [StarLabsLtd/firmware#133]
If I suspend the system while it is plugged in and then close the lid, the laptop wakes up.  Then, if I open the lid, it suspends again!  I feel this is the wrong way around...

(Additionally, pressing the power button or other keys on the keyboard does not always seem to wake the laptop up.)

**Comment by Sean-StarLabs** [comment]
Duplicate of #126
