### ISSUE TITLE
[StarBook mk VI][EC] Feature request: setting charging thresholds from the OS

### ISSUE THREAD

**Issue by cklamra** [StarLabsLtd/firmware#146]
As far as I understand, for now it's only possible to set the charging thresholds in the BIOS settings. It would be very useful to be able to set them directly from the OS – I would prefer to use a 60/80% threshold for daily use to keep the battery sane, but have an option to fully charge the laptop when necessary (without rebooting). 
This would make it possible to add support for tools such as Battery Health Charging Gnome extension:
[https://github.com/maniacx/Battery-Health-Charging](https://github.com/maniacx/Battery-Health-Charging)
[https://maniacx.github.io/Battery-Health-Charging/](https://maniacx.github.io/Battery-Health-Charging/)

**Comment by Sean-StarLabs** [comment]
It's possible, but it would create a dependency, so it's not something we want to do. The plan is to publish the EC code fairly soon, so it'll then be possible to build it to be controlled via ACPI.
