### ISSUE TITLE
[StarBook mkVI Intel coreboot]  Timeout from EC

### ISSUE THREAD

**Issue by divico** [StarLabsLtd/firmware#149]
Since upgrading to coreboot `9.01` (ite `1.23` unchanged) I've been experiencing sporadic EC timeouts. When turning on the machine, it  stays on the starlabs logo for too long before some EC related errors are printed. I haven't found out how to reproduce this yet, but it has happened twice since the update.

![image](https://github.com/StarLabsLtd/firmware/assets/11789268/a711e871-d332-46a1-9de0-837a9398a826)

Long press on the power buttons solves the issue, until the next time...

Any idea how to reproduce / solve this?

**Comment by Sean-StarLabs** [comment]
> reproduce

Press a key before edk2 has initialised the kbc

> solve

Use a stable build, or a newer testing build
