### ISSUE TITLE
Starlab mkIII coreboot

### ISSUE THREAD

**Issue by ghost** [StarLabsLtd/firmware#16]
I am having battery problems with the coreboot firmware, it does not start from low battery levels below 30% apparently.

**Comment by casanova8211** [comment]
Also after the switch to coreboot, I get the mouse stucked after a boot, F10 does not unlock it. After a reboot it works back to normal again.

**Comment by Sean-StarLabs** [comment]
LabTop Mk III? If you update to version 5, it'll fix those two issues :)
