### ISSUE TITLE
Starbook mkVI stopped charging over usb C

### ISSUE THREAD

**Issue by r-vdp** [StarLabsLtd/firmware#160]
Suddenly my starbook mkVI stopped charging over usb C.

The laptop reports that it's charging but it doesn't draw any power and the battery percentage keeps on going down.

The charging LED flashes multiple times when I plug a cable.

I don't have the barrel charger with me to test currently.

The laptop will intermittently charge for a bit, and then stops again. It is plugged into the starbook power brick.

What can I do? This is obviously a major issue.

**Comment by Sean-StarLabs** [comment]
It's calibrating; either let is run to empty, or update the firmware as the latest build has an option to disable the calibration

**Comment by r-vdp** [comment]
I just rebooted and set the LEARN setting to disabled, but it's still discharging.

The EC did not get updated though, maybe that's related?

**Comment by r-vdp** [comment]
@Sean-StarLabs the battery ran down to 0%, the laptop shut off, and now it doesn't turn on anymore. No LEDs are on either, and the power button doesn't do anything. 

Is this normal? How can I get the laptop to turn on again?

**Comment by Sean-StarLabs** [comment]
With the charger in or out?

**Comment by r-vdp** [comment]
> With the charger in or out?

In both cases there's no response from the laptop. Black screen and no LEDs.

**Comment by r-vdp** [comment]
Any idea? My laptop is bricked now.

**Comment by divico** [comment]
> Any idea? My laptop is bricked now.

It is most likely not bricked and will start just fine if you plug in the barrel jack. I had the same issue #153 which is solved by disabling LEARN on latest firmware.

**Comment by r-vdp** [comment]
> It is most likely not bricked and will start just fine if you plug in the barrel jack. I had the same issue #153 which is solved by disabling LEARN on latest firmware.

Ok. Well it's effectively bricked right now because I won't have access to the barrel jack cable until beginning next week. 

This is really very annoying.

**Comment by Sean-StarLabs** [comment]
> I had the same issue https://github.com/StarLabsLtd/firmware/issues/153

No LEDs isn't the same,,,

So, updated to 24.03, did you shut down after installing or rebooting the BIOS setup?
After that, the battery ran down to 0%. Was that with or without the charger connected?
Which charger and cable are you using?

**Comment by r-vdp** [comment]
I rebooted after the firmware flash and went into the firmware setup to reapply my settings. 

Then it ran the battery down with the charger connected. It's the starbook charger that came with the laptop, connected with a good quality usb cable. 

Once the battery was empty, the laptop turned off and since then I can't turn it on anymore.

**Comment by Sean-StarLabs** [comment]
Not shutting down means a bunch of things don't get reset, so when the BIOS you just flashed starts for the first time - it's reading its config from junk data - very unlikely that it'll work.

All you can really "try" is disconnecting the battery, leaving it for about 15 minutes, and then reconnecting it. If that doesn't work, the BIOS region will need to be reprogrammed with a hardware programmer. If you need help with that, ping support as there a few ways to play it.

**Comment by r-vdp** [comment]
Hi Sean

Could you explain me a bit how the procedure goes so that I can estimate whether I can do this myself or not? 

Thanks, 
Ramses

15 mai 2024, 22:42 de ***@***.***:

**Comment by Sean-StarLabs** [comment]
Pretty much the same as this: https://support.starlabs.systems/kb/guides/installing-slash-recovering-firmware-with-external-programmer

Only real difference is that you can't use a clip, it has to be a 12-pin FPC.
