### ISSUE TITLE
[StarLite Mk IV] Missing coreboot options?

### ISSUE THREAD

**Issue by CommonLoon102** [StarLabsLtd/firmware#164]
Since I have switched to coreboot, I wanted to install the Coreboot Configurator, but it has been retired.
https://support.starlabs.systems/kb/guides/coreboot-configurator

Specifically, I wanted two things. Turn off the microphone and limit the max charge to 90%.
Both options are missing from the BIOS.

I suppose turning off the webcam would turn off the microphone as well? Because for input device I see "Microphone - USB 2.0 Camera". OK, so I tried it, the answer is yes.

What I still miss though is limiting the max charge. Is there a reason why the option is not showing up in the BIOS?

**Comment by Sean-StarLabs** [comment]
The Lite Mk IV doesn't have an option to limit the charge level

**Comment by CommonLoon102** [comment]
Is this a hardware limitation?
