### ISSUE TITLE
Lite Mk I ITE Update Version Seems Wrong

### ISSUE THREAD

**Issue by ryanteck** [StarLabsLtd/firmware#17]
Hi,

I've been updating my Mk1 with the latest Bios and Found a version of 1.05.10 on the github page.

However when I try to upgrade it, it says that the version is 1.05.06 and looking at the files it seems that the one marked 1.05.10 is actually 1.05.06.

Is there a newer version, or is it that 1.05.06 is the latest?

Thanks

**Comment by Sean-StarLabs** [comment]
Hey.

1.05.06 is the latest, I've just fixed the version number for the download with 3365eb2db16a513b1bc8bff4c0f2a84c3b943028
