### ISSUE TITLE
[*] - Add an option to disable the lid switch

### ISSUE THREAD

**Issue by Sean-StarLabs** [StarLabsLtd/firmware#172]

**Comment by DevenBL** [comment]
Does not function properly in the starlite mk V closing the detachable keyboard on the tablet causes it to: suspend? (I think. It does something and becomes unresponsive for a bit. Sometimes recovers sometimes doesn't when it doesn't the power led flashes rapidly). No matter what option is selected in bios enabled or disabled. Firmware 24.10

**Comment by Sean-StarLabs** [comment]
> Firmware 24.10

Only raise issues for stable releases

> Does not function properly 

It stops the firmware requesting S3 entry when the cover is closed - that's for sure.
