### ISSUE TITLE
[StarLite Mk V] Keyboard Backlight flickers every 48 seconds

### ISSUE THREAD

**Issue by PhilT** [StarLabsLtd/firmware#177]
Not sure if this is a firmware issue but when plugged in the keyboard backlight turns off and back on immediately every 48 seconds (I timed it for 3 off/on instances).

Running on NixOS but I'm pretty sure it was doing the same thing with Linux Mint that was installed when I received it last week.

**Comment by Sean-StarLabs** [comment]
Current way to update: https://github.com/StarLabsLtd/starlite_keyboard_update
