### ISSUE TITLE
[Feature Request] Ability to set charge threshold / Limit charge at 80 %

### ISSUE THREAD

**Issue by mystic-githuber** [StarLabsLtd/firmware#19]
Ability to set charge threshold / Limit charge at 80 %. 

Setting it to start back at 40% or any dynamic range would be great.

**Comment by mystic-githuber** [comment]
This would help in improving battery life.

**Comment by Sean-StarLabs** [comment]
We're going to make it configurable when we release our open-source EC. Until then, it is fixed at 95% :)
