### ISSUE TITLE
[StarLite Mk V - Magnetic Keyboard] Make Fn lock Configurable

### ISSUE THREAD

**Issue by grumpyoldbloke** [StarLabsLtd/firmware#192]
Is there a simple way to change the Fn key to allow the function keys to have priority? I can't find a way to do this.

**Comment by pdfrod** [comment]
I've been searching for a way to do this as well. [This help article](https://support.starlabs.systems/kb/guides/how-to-use-the-function-keys) suggests that using the **lock** does just that, but I can't find any lock key.

**Comment by echo-devnull** [comment]
I've asked Sean this via email once I received my MKV.  It seems it was not something this machine offers (offered?)

But seeing as he changed the title, he might be looking at adding some firmware option perhaps?  That would be a fantastic addition to an already fantastic machine. Until then; I use a Lenovo Thinkpad Bluetooth keyboard.

**Comment by Anachron** [comment]
@Sean-StarLabs is this something that is possible with a Firmware upgrade?

**Comment by Sean-StarLabs** [comment]
Yes

**Comment by pdfrod** [comment]
Any quick fix while we wait for a proper solution?

I tried forcing `fn_lock_state` to `UNLOCKED` by using `ec_write(ECRAM_FN_LOCK_STATE, UNLOCKED)` [here](https://github.com/StarLabsLtd/coreboot/blob/4f22dfa8ac033502d97e1a4e596041b12376fb64/src/ec/starlabs/merlin/ite.c#L218), but that didn't make any difference.

**Comment by Sean-StarLabs** [comment]
You're brave :)

> Any quick fix while we wait for a proper solution?

We've got a Windows tool that can program them if you want that, Linux one is probably a week away

**Comment by pdfrod** [comment]
> You're brave :)

I like a good challenge :smile: 

> > Any quick fix while we wait for a proper solution?
> 
> We've got a Windows tool that can program them if you want that, Linux one is probably a week away

Just to make sure I understod, this tool allows working on the code that would fix the problem? And the fix would work on Linux? If that's the case sure, I wouldn't mind booting into Windows to give it a try.

**Comment by Sean-StarLabs** [comment]
program = update/install

**Comment by pdfrod** [comment]
Not sure if I understand. But yeah, if there's a tool that I can use, let me know where to find it.

**Comment by Sean-StarLabs** [comment]
[ANSI.zip](https://github.com/user-attachments/files/17340788/ANSI.zip)
[ISO.zip](https://github.com/user-attachments/files/17340791/ISO.zip)

**Comment by Sean-StarLabs** [comment]
Current way to update: https://github.com/StarLabsLtd/starlite_keyboard_update

**Comment by gzagatti** [comment]
> Current way to update: https://github.com/StarLabsLtd/starlite_keyboard_update

This issue has been closed as completed. Will the option to lock the Fn key on the StarLite be part of the next firmware upgrade, or the only way to do that will be by following the instructions in the linked repo.

**Comment by gzagatti** [comment]
@Sean-StarLabs I tried using the above tool. Unfortunately, I was not able to modify the Fn lock. Once booted into the tool, I was logged into a Windows environment. There were two programs which when launched displayed a text box with unreadable characters. Once I ran the programs, the keyboard got reprogrammed. 

I first ran the ANSI program, and did not notice any changes to the keyboard (my keyboard is US). I then ran the ISO program, and my keyboard got completely misconfiguration which suggests that these programs indeed modify the keyboard. My testing each key of the mis-configured keyboard, I was then able to re-run the ANSI program to reset the keys to the default.

My question is how do I configure the program to have the FN key locked? The unreadable characters in the program probably contain instructions for doing that, but I cannot read them.

**Comment by Sean-StarLabs** [comment]
Press `Fn` + `Esc`

**Comment by pdfrod** [comment]
Ah ,so that's how it works! I was quite confused as I wasn't spotting any difference after running the update.

Anyway, I tried the shortcut and it works nicely. Thank you so much!

**Comment by gzagatti** [comment]
Same here. Thanks for the quick response!
