### ISSUE TITLE
[StarLite Mk V] Orientation from sensor seems to be wrong

### ISSUE THREAD

**Issue by TheJackiMonster** [StarLabsLtd/firmware#199]
From one day to another the auto-rotate feature automatically flipped my screen vertically if I hold it horizontally. In vertical layout it rotates the screen properly but in horizontal layout, it's 180° wrong.

I'm not sure how this issue was caused because I didn't manually configure anything. But maybe somehow GNOME has reconfigured the sensor matrix during the attachment process of the keyboard because I locked auto-rotate at some point? Wild guess but at first the orientation in tablet mode was correct but when attaching it, it automatically flipped 180° to be upside down. I applied proper orirentation via GNOME control center multiple times until it was correct again when attached but now the auto-rotate seems to be wrong.

Either way I'm not sure whether this is a firmware issue or a GNOME issue at this point. But does anyone know a workaround or fix to reset orientation settings? Otherwise I assume I need to reinstall the whole system which is kind of annoying. Especially when I'm not sure how to prevent this issue (with exception of never touching auto-rotate ever again because it just seems to break stuff).

**Comment by Sean-StarLabs** [comment]
Please see: https://support.starlabs.systems/kb/guides/starlite-fixing-rotation-on-older-kernel
