### ISSUE TITLE
[StarLite Mk V] Disabling camera in Coreboot disables also the Webcam 

### ISSUE THREAD

**Issue by AndrzejTunkiel** [StarLabsLtd/firmware#202]
Running lsusb with everything enabled:
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 003: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 004: ID 1018:1006  
Bus 001 Device 005: ID 8087:0aaa Intel Corp. Bluetooth 9460/9560 Jefferson Peak (JfP)
Bus 001 Device 006: ID 0bda:5830 Realtek Semiconductor Corp. USB2.0 camera
Bus 001 Device 007: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
Bus 001 Device 008: ID 1bcf:284d Sunplus Innovation Technology Inc. USB 2.0 Camera
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub

Running lsusb with 'Camera' disabled in coreboot:
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 003: ID 8087:0aaa Intel Corp. Bluetooth 9460/9560 Jefferson Peak (JfP)
Bus 001 Device 004: ID 1018:1006  
Bus 001 Device 005: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub

The expected behavior is that the (back) camera only gets disabled, but the Webcam (front) is still enabled. This would be beneficial as some videoconferencing solutions (Google Duo/Meet) struggle to switch between the cameras.

**Comment by Sean-StarLabs** [comment]
It's a child device so not possible (same way disabling the accelerometer will knock out the touchscreen)
