### ISSUE TITLE
[StarLite Mk V] Sometimes crashing on lid close

### ISSUE THREAD

**Issue by PhilT** [StarLabsLtd/firmware#210]
I've noticed that sometimes when I close the lid the tablet starts flashing the power led very rapidly. I can then only turn it back on by holding the power button for about 10 seconds.

I'm not using the device a great deal at the moment so I'm not sure if it's something in particular that's running but I'm normally running several terminals and Firefox on NixOS.

I'll try to test a bit more and report back but other can add thumbs if anyone else is getting issues.
 
On a more general note. Are the outstanding issues with this device being worked on? It's been a little while since it was released and I feel it could do with a bit more polish.

Thanks.

**Comment by Sean-StarLabs** [comment]
Not known, and would need version numbers to look into.

> Are the outstanding issues with this device being worked on?

Yes

**Comment by PhilT** [comment]
Version numbers?

**Comment by Sean-StarLabs** [comment]
Kernel and firmware

**Comment by PhilT** [comment]
Also, sometimes it doesn't suspend at all. Screen goes blank (as far as I can tell) but power LED stays on.

**Comment by Sean-StarLabs** [comment]
Might be #183, can you trying with the tray out?

**Comment by PhilT** [comment]
With the tray out it seems to sleep pretty quickly but Firefox still crashes and closing the lid is still a bit hit and miss.

**Comment by Sean-StarLabs** [comment]
The only other known thing floating around is the 6.9 kernel, so worth trying 6.8, but I'd imagine it's something software related - tried another distro?

**Comment by PhilT** [comment]
> tried another distro?
I haven't but I was contemplating it. I'll give that a try when I get the chance.
I'll also check 6.8 as well.
Thanks.

**Comment by dchang0** [comment]
I've seen the same thing as the OP occasionally. I have also seen the same extremely rapid flashing power LED sometimes when attempting to turn on the tablet from power-off. I press the power button, the LED comes on, flashes extremely rapidly for a few seconds, and then goes dark, and the tablet stays off.

**Comment by Sean-StarLabs** [comment]
@dchang0 Sounds right - that's it going from G3 to S5 (mechanically off to electronically off)

**Comment by dchang0** [comment]
> @dchang0 Sounds right - that's it going from G3 to S5 (mechanically off to electronically off)

Hmm. Well, the intention is to turn the tablet on (from fully off to fully on), so it is puzzling.
I end up having to try a few times, and then it finally gets the point and turns on.

So, are you saying that the super-fast flashing of the power LED always means that the tablet is turning off electronically? If so, then that absolutely fits the OP's symptoms, but it is weird for my situation.

**Comment by Sean-StarLabs** [comment]
> Hmm. Well, the intention is to turn the tablet on (from fully off to fully on), so it is puzzling.
I end up having to try a few times, and then it finally gets the point and turns on.

It's there to prevent accidentally turning it on - simply put, it's a double-press if there isn't a charger connected.

> So, are you saying that the super-fast flashing of the power LED always means that the tablet is turning off electronically? If so, then that absolutely fits the OP's symptoms, but it is weird for my situation.

No, flashing power LED is changing power states.

**Comment by Sean-StarLabs** [comment]
Fixed with d6de2690dd547a014309086a9cc435e2b58f091e
