### ISSUE TITLE
[StarLite Mk V] Add option to disable extremely bright led's

### ISSUE THREAD

**Issue by DevenBL** [StarLabsLtd/firmware#214]
Please add an option in the bios or somewhere else to disable the external led's

**Comment by Sean-StarLabs** [comment]
Which ones? Why?

**Comment by DevenBL** [comment]
The top LED near the power button is extremely bright at night. To have it either solid or pulsating makes sleep difficult if the tablet is on or suspended in the same room.
Potentially the charging port led as well although that does not currently seem to be as much of an issue.

**Comment by Anachron** [comment]
I agree. I wish all devices that can be used in the sleeping room can have their LEDs turned down/off.

**Comment by Sean-StarLabs** [comment]
Do you care if it does the "breathing"? It'll be possible to do, but I don't know how off the top of my head. Simple on/off for S3 with limited brightness is easy.

**Comment by mixmastamyk** [comment]
Yes, too bright and too white.  Dim and/or orange/red would be better.

Unfortunately I also use it to know how long I've held the power button (blinks at 2 secs I think) to get it to come out of suspend.  So please allow the blink to happen even if you have a setting to turn it off.

**Comment by gzagatti** [comment]
It would be great to be able to adjust this light. It is indeed too bright.

If no customization is possible, I would at least like to be able to switch it off completely as it is very distracting.

**Comment by DevenBL** [comment]
An option to make the light not on all the time/not at max brightness seems to be the common point here. Some people however seem to want to retain the information conveyed by the light. 
Although i do not particularly care about the specifics of the implementation: 
Perhaps the option should be to have the power button light normally off and only communicate information through light when pressed? 

Fundamentally the problem is that the lights are on all or most of the time. Whatever solution you pick so long as there is an option to have the lights are on less in some way shape or form it would be an improvement.
What even is the best practice for this? On the steamdeck valve just allows you to turn the led off and you do things blindly. However since the led is also used when updating the firmware you would likely not want to disable the triple flash functionality when upgrading.

**Comment by Sean-StarLabs** [comment]
Fixed with 6287b93e88154b7013df782a2e57405f403af339

**Comment by thebatdan** [comment]
I've updated to firmware 25.01 from LVFS, the bright LEDs seem to be back and the option to change the brightness seems to have disappeared from the Bios. Has there been a regression on this?

**Comment by Sean-StarLabs** [comment]
Missed in upstreaming - will have it back in the next release:
https://review.coreboot.org/c/coreboot/+/86240
