### ISSUE TITLE
Firmware update failed: Firmware version formats were different

### ISSUE THREAD

**Issue by stan-janssen** [StarLabsLtd/firmware#23]
I wanted to test the 7.6 firmware following my report of #21, so I added the testing branch to lvfs. Using the fwupd-gui, I get the following error when trying to upgrade from 7.4 to 7.6: 

![firmware-update-failed](https://user-images.githubusercontent.com/12174852/146396230-20660f00-f237-420f-a09b-747755921796.png)

Anything I should try?

**Comment by Sean-StarLabs** [comment]
You'll need to use `fwupdmgr update --force` to install 7.6

**Comment by stan-janssen** [comment]
That worked, thanks.
