### ISSUE TITLE
SysRq key emits Alt+SysRq

### ISSUE THREAD

**Issue by cassidyjames** [StarLabsLtd/firmware#28]
I noticed if I accidentally hit the SysRq key on elementary OS, my StarBook takes a screenshot of the current window. This is set to Alt+PrntScr by default, so it seems that's what is being interpreted here. Would it be possible to not emit Alt included in that shortcut since it's not obvious why hitting it takes a screenshot?

This also makes it difficult to bind the key to something else I'd prefer, as the OS only sees it as a combination of the two Alt+SysRq keys when creating custom shortcuts.

**Comment by Sean-StarLabs** [comment]
Will adjust when EC source code publshed
