### ISSUE TITLE
Coreboot Source code

### ISSUE THREAD

**Issue by maryandmaxcakeyogurt** [StarLabsLtd/firmware#36]
I can find Coreboot binaries, but no source code.
Could you please release the source code?

**Comment by Sean-StarLabs** [comment]
It's here - https://github.com/coreboot/coreboot

**Comment by maryandmaxcakeyogurt** [comment]
Coreboot is GPL. If you distribute binaries, you must also distribute the source code.
Currently, this is a violation of the GPL.

**Comment by maryandmaxcakeyogurt** [comment]
You must distribute the source code corresponding to the binary in your own repository (or on a non-GitHub web server), rather than pointing to someone else's repository.

**Comment by Sean-StarLabs** [comment]
Not sure I follow - Our coreboot binaries are built from there?

**Comment by maryandmaxcakeyogurt** [comment]
For example, the source code corresponding to [this binary](https://github.com/StarLabsLtd/firmware/tree/master/StarBook/MkV/coreboot/7.10) must be distributed (e.g., as a tarball) on the Star Labs server.
Linking to someone else's server will cause problems.

**Comment by Sean-StarLabs** [comment]
Having a copy of it somewhere else, and adding a tarball will just complicate things. If you want to see exactly what's it that version, just use the commit hash

**Comment by maryandmaxcakeyogurt** [comment]
Ah, I misunderstood. I am sorry.

I have a suggestion related to this, which I will raise in a separate Issue.
This Issue is closed.
