### ISSUE TITLE
[Future request]Control Caps Swap Option

### ISSUE THREAD

**Issue by ghost** [StarLabsLtd/firmware#37]
Could you please provide an option to swap Control and Caps Lock?

**Comment by danth** [comment]
This can be done within Linux using various software. See https://www.emacswiki.org/emacs/MovingTheCtrlKey for example

**Comment by Sean-StarLabs** [comment]
It's possible but much better to handle that with software because you can map almost anything you want, a firmware option would be much less flexible.
