### ISSUE TITLE
Countermeasure against misoperation of the power button

### ISSUE THREAD

**Issue by ghost** [StarLabsLtd/firmware#39]
StarLabs laptops have the power button near Backspace. This is a bad hardware design that induces misoperation.

Is there any way to cover this bad hardware with firmware? For example, it only works when pressed at the same time as the Fn key.

**Comment by Sean-StarLabs** [comment]
The standard 3-second delay for the power menu is sufficient to counter accidental presses. Binding it to a key that's not standardised nor self-explanatory would be a recipe for disaster.

We're looking into mapping a keycode to it (see #27) and then you can do whatever you want with it.
