### ISSUE TITLE
[StarLite Mk III] USB ports cause an issue with PS2 initialisation

### ISSUE THREAD

**Issue by barbastrejo7** [StarLabsLtd/firmware#41]
I had this problem while manjaro while testing how that distro was on the mkIII, but now having on Debian too.
Basically after a boot or reboot, on the login page the keyboard does not work, some F keys work, but no numbers symbols or letters.

**Comment by Sean-StarLabs** [comment]
Fixed with 8a1eb1993d9e48305a82b670c34bafefa9730594, this will be included in the next release
