### ISSUE TITLE
[StarLite Mk III] S3 Resume fails in FSP M

### ISSUE THREAD

**Issue by ghost** [StarLabsLtd/firmware#42]
When I close the lid of the lite mkIII and reopen, nothing happens, the power led is on but the pc will not come back from sleep. I need to force reboot every time.

**Comment by igor-kobzev** [comment]
Is the 8.02 update not for StarLite IV? I couldn't install it. Only 4.17.

**Comment by Sean-StarLabs** [comment]
`8.02` exists for all of our laptops. For the Lite Mk IV, it's currently in the testing remote.

**Comment by igor-kobzev** [comment]
Gotcha, I'll wait. May I ask, just out of curiosity, why the radical jump in version number though?

**Comment by Sean-StarLabs** [comment]
To bring it in line with our other version numbers. coreboot only tags a release every three months, which makes it difficult to use theirs.

**Comment by Brianetta** [comment]
@Sean-StarLabs Is this the same issue that I raised by email?

**Comment by Sean-StarLabs** [comment]
@Brianetta It is indeed.

**Comment by Sean-StarLabs** [comment]
Bootblock needs to be relocatable for it to work, which coreboot doesn't support.
