### ISSUE TITLE
[StarLite Mk IV] - Broken link in readme to latest firmware

### ISSUE THREAD

**Issue by maxengel** [StarLabsLtd/firmware#44]
[This link to the current 4.17 Coreboot FW](https://github.com/StarLabsLtd/firmware/raw/master/StarLite/MkIV/coreboot/4.17/efi-I4.zip) is currently broken which is present in the readme at [the project page](https://github.com/StarLabsLtd/firmware).

**Comment by Sean-StarLabs** [comment]
It should be broken - until the firmware is pushed to stable
