### ISSUE TITLE
Lite mkIII turns off with battery around 40%

### ISSUE THREAD

**Issue by barbastrejo7** [StarLabsLtd/firmware#45]
From the last 2 days I started having this issue that when the battery falls to around 40% the laptop turns off out of nothing. I was using Debian and having other problems, I changed to manjaro, it's a bit more stable but still having the issue. On debian, after the device turning off, after plugging the cable the battery was shows to be 0-5%, on manjaro around 40-50%.

**Comment by Sean-StarLabs** [comment]
That sounds like a hardware issue, rather than firmware. If you ping an email to support@starlabs.systems, we can look into that for you :)
