### ISSUE TITLE
Power led on after shutdown

### ISSUE THREAD

**Issue by barbastrejo7** [StarLabsLtd/firmware#51]
Just upgraded to 8.02 on the lite mkIII. Many good improvements, now all USB are working properly and Bluetooth too, the space bar problem is fixed too, thanks for the great work! I have only this small bug now, when I shutdown the machine the led power remain on, pressing power button for around 20s turns it off, then I can press power to start the machine again.

**Comment by Sean-StarLabs** [comment]
That's the same as #42 - still working on that one!

**Comment by barbastrejo7** [comment]
Oh I see, thanks for explaining. No hurries.
