### ISSUE TITLE
ITE new version not available on lite mkIII via fwupd

### ISSUE THREAD

**Issue by barbastrejo7** [StarLabsLtd/firmware#52]
I am running ITE version 1.03, and saw there's 1.13 and 1.14, but I am unable to upgrade via gnome-firmware or fwupd.

**Comment by Sean-StarLabs** [comment]
They're in testing, if you want to install them before they are marked as stable, you'll need to `fwupdmgr enable-remote lvfs-testing`

**Comment by barbastrejo7** [comment]
Oh I see, thanks for the info.
