### ISSUE TITLE
Star Lite IV: cannot update to lastest release via fwupd

### ISSUE THREAD

**Issue by elagost** [StarLabsLtd/firmware#53]
Using a Linux Mint 21 Live USB and the instructions here: https://support.starlabs.systems/kb/updates/installing-updates-from-the-lvfs

running `fwupdmgr get-devices` showd in red text (BIOS Locked), and `fupdmgr upgrade` shows a line telling me I can't update due to a locked BIOS. I'm currently on coreboot 4.17. Could be similar to https://github.com/StarLabsLtd/firmware/issues/50 ?

**Comment by Sean-StarLabs** [comment]
No, that's a known bug in fwupd. Building the new version for Ubuntu now, should be done by the end of the day. They're already built for Manjaro and Debian.

**Comment by elagost** [comment]
Thank you, I appreciate it. I will test sometime this weekend, and if it's still not working, use a debian live usb.

**Comment by Sean-StarLabs** [comment]
Packages have been published for focal and jammy: https://launchpad.net/~starlabs/+archive/ubuntu/main/+packages

**Comment by elagost** [comment]
Thank you! Updated to 8.05 now.
