### ISSUE TITLE
F1-F12 function keys

### ISSUE THREAD

**Issue by alternateved** [StarLabsLtd/firmware#64]
Hello!

Currently in BIOS settings there only seems to be an option to switch fn key with ctrl. Is there a way to switch F1-F12 keys with their functions (so pushing F1 gives F1 an not its function mute)? If not, could there be a way?

I am currently using StarBook MkVI AMD with AMI (as there seems to be no other option).

Kind regards,
alternateved

**Comment by Sean-StarLabs** [comment]
Sure is - press the `lock` key

**Comment by alternateved** [comment]
Ah! Perfect. Honestly I did not notice the existence of the `lock` key. Silly me. Thank you!

**Comment by Sean-StarLabs** [comment]
No problem :)
