### ISSUE TITLE
[StarBook Mk VI - AMD - AMI] Malformed ACPI

### ISSUE THREAD

**Issue by Sean-StarLabs** [StarLabsLtd/firmware#73]
`Malformed MSFT vendor event: 0x02`

**Comment by tsmithe** [comment]
I don't know if this is relevant, but in going through a similar log on a different platform seemingly related to #75, I noticed the same string to the one in this issue body.  The different platform in question is a Thinkpad E14 Gen 3 with a 5800U, and its log (also exhibiting #75) can be found at https://gitlab.freedesktop.org/drm/amd/-/issues/2403#note_1777940 (see line 3243).

**Comment by Sean-StarLabs** [comment]
Turns out it's a kernel bug
