### ISSUE TITLE
[StarBook MK VI Intel] Reboot does not work

### ISSUE THREAD

**Issue by cichy1173** [StarLabsLtd/firmware#74]
Hi. I have Starbook MK VI Intel i7-1260p with Fedora 37 and encrypted drive and coreboot.

When I want to reboot system, it is not possible. Computer goes into EFI, but not operating system. I have to manually turn off computer and turn on it again to boot into OS. 

https://user-images.githubusercontent.com/32648503/218253278-51698757-dcc0-40ea-802e-fa840ab6aad8.mp4

**Comment by Sean-StarLabs** [comment]
Is that in `8.27`?

**Comment by cichy1173** [comment]
> Is that in `8.27`?

Yes
