### ISSUE TITLE
[StarBook Mk VI - AMD] Trouble with s2idle

### ISSUE THREAD

**Issue by tsmithe** [StarLabsLtd/firmware#76]
The platform reports `s2idle` support in `/sys/power/mem_sleep`, but attempting to enter suspend causes the system to lock up.  Moreover, the `amd_pmc` module does not load correctly, and the ACPI FADT doesn't seem to report s2idle support.  See the comments around here for a little more information:  https://gitlab.freedesktop.org/drm/amd/-/issues/2403#note_1774129

I am on the AMI firmware (since coreboot doesn't yet seem to be available, following #65), but if (when it becomes available) switching to coreboot would resolve this bug, that would be fine by me.

**Comment by Sean-StarLabs** [comment]
Working on it regardless - about 80% of the way through the dsdt :/

**Comment by superm1** [comment]
There's an issue that some newer Intel hardware doesn't support lane switch when transitioning to L0s, so if disabling aspm helps try to just disable L0s to narrow down.
