### ISSUE TITLE
Inconsistent memory map preventing hibernation

### ISSUE THREAD

**Issue by R-VdP** [StarLabsLtd/firmware#81]
Hibernation of my StarBook Mk VI (Intel, coreboot) fails because the memory map passed to the kernel seems to be different on every boot. Below are a couple of memory maps that I captured, you can notice a difference for instance in the fourth region,  which has a different ending address in all three mappings.

Is there any way to deal with this so that hibernation can be used?

```
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x0000000000000000-0x0000000000000fff] reserved
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x0000000000001000-0x000000000009ffff] usable
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x00000000000a0000-0x00000000000fffff] reserved
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x0000000000100000-0x000000007252dfff] usable
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x000000007252e000-0x000000007252ffff] ACPI data
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x0000000072530000-0x00000000755aafff] usable
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x00000000755ab000-0x00000000755abfff] ACPI data
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x00000000755ac000-0x0000000076613fff] usable
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x0000000076614000-0x0000000076617fff] ACPI data
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x0000000076618000-0x000000007661cfff] usable
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x000000007661d000-0x0000000076621fff] ACPI data
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x0000000076622000-0x0000000076635fff] usable
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x0000000076636000-0x0000000076637fff] ACPI data
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x0000000076638000-0x0000000076809fff] usable
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x000000007680a000-0x000000007694dfff] reserved
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x000000007694e000-0x0000000076951fff] ACPI NVS
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x0000000076952000-0x0000000076959fff] ACPI data
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x000000007695a000-0x000000007695afff] usable
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x000000007695b000-0x00000000803fffff] reserved
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x00000000ff030000-0x00000000ff06ffff] reserved
fév 21 23:02:31 starbook kernel: BIOS-e820: [mem 0x0000000100000000-0x000000087fbfffff] usable

fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x0000000000000000-0x0000000000000fff] reserved
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x0000000000001000-0x000000000009ffff] usable
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x00000000000a0000-0x00000000000fffff] reserved
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x0000000000100000-0x00000000750a0fff] usable
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x00000000750a1000-0x00000000750a3fff] ACPI data
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x00000000750a4000-0x00000000755d7fff] usable
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x00000000755d8000-0x00000000755d8fff] ACPI data
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x00000000755d9000-0x0000000076613fff] usable
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x0000000076614000-0x0000000076617fff] ACPI data
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x0000000076618000-0x000000007661cfff] usable
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x000000007661d000-0x0000000076621fff] ACPI data
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x0000000076622000-0x0000000076635fff] usable
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x0000000076636000-0x0000000076637fff] ACPI data
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x0000000076638000-0x0000000076809fff] usable
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x000000007680a000-0x000000007694dfff] reserved
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x000000007694e000-0x0000000076951fff] ACPI NVS
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x0000000076952000-0x0000000076959fff] ACPI data
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x000000007695a000-0x000000007695afff] usable
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x000000007695b000-0x00000000803fffff] reserved
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x00000000ff030000-0x00000000ff06ffff] reserved
fév 25 00:46:55 starbook kernel: BIOS-e820: [mem 0x0000000100000000-0x000000087fbfffff] usable

fév 25 11:04:07 starbook kernel: BIOS-provided physical RAM map:
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x0000000000000000-0x0000000000000fff] reserved
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x0000000000001000-0x000000000009ffff] usable
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x00000000000a0000-0x00000000000fffff] reserved
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x0000000000100000-0x000000007255bfff] usable
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x000000007255c000-0x000000007255dfff] ACPI data
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x000000007255e000-0x00000000750abfff] usable
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x00000000750ac000-0x00000000750acfff] ACPI data
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x00000000750ad000-0x00000000755d7fff] usable
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x00000000755d8000-0x00000000755d8fff] ACPI data
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x00000000755d9000-0x0000000076613fff] usable
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x0000000076614000-0x0000000076617fff] ACPI data
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x0000000076618000-0x000000007661cfff] usable
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x000000007661d000-0x0000000076621fff] ACPI data
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x0000000076622000-0x0000000076635fff] usable
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x0000000076636000-0x0000000076637fff] ACPI data
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x0000000076638000-0x0000000076809fff] usable
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x000000007680a000-0x000000007694dfff] reserved
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x000000007694e000-0x0000000076951fff] ACPI NVS
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x0000000076952000-0x0000000076959fff] ACPI data
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x000000007695a000-0x000000007695afff] usable
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x000000007695b000-0x00000000803fffff] reserved
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x00000000ff030000-0x00000000ff06ffff] reserved
fév 25 11:04:07 starbook kernel: BIOS-e820: [mem 0x0000000100000000-0x000000087fbfffff] usable
```

**Comment by Sean-StarLabs** [comment]
Short answer is no, UPL mentioned in #71 might actually fix it as it avoids the resource allocator script and uses hobs.

**Comment by divico** [comment]
I'm having the same issue, resuming from hibernation fails often with
```
PM: hibernation: Image mismatch: architecture specific data
PM: hibernation: Failed to load image, recovering.
```
Could you tell me if this can be fixed with a firmware update, if so which version should I use on my Starbook MkVIr2-Intel?

**Comment by Sean-StarLabs** [comment]
What's "often"?
What firmware are you running?

**Comment by divico** [comment]
> What kernel you using?

Using `6.15.9` (arch linux-lts)

**Comment by Sean-StarLabs** [comment]
> Can we help fix this by providing some more logs or testing?

Afraid not

**Comment by sim31** [comment]
Experiencing this as well. But for me it started happening fairly recently, since 25.10 version I think. And I was using hibernation before then a lot. Kernel: 6.17.5-arch1-1.

**Comment by divico** [comment]
> Experiencing this as well. But for me it started happening fairly recently, since 25.10 version I think. And I was using hibernation before then a lot. Kernel: 6.17.5-arch1-1.

I also did not experience this in the first years of using my Starbook. For sure I did not have it on firmware versions <`24`. I'm not sure when it started. 

I don't understand why more people aren't reporting this issue. It's such a significant regression for laptops IMHO.

**Comment by divico** [comment]
Is this fix part of coreboot `25.12` firmware release? The changelog states  "Fixed resuming from hibernation (S4)"

**Comment by Sean-StarLabs** [comment]
I've been unable to replicate this since 26.02 on multiple boards; nothing directly changed to address it, but can you give it a whirl? I think if it's still happening, we need to look for an external trigger

**Comment by divico** [comment]
> I've been unable to replicate this since 26.02 on multiple boards; nothing directly changed to address it, but can you give it a whirl? I think if it's still happening, we need to look for an external trigger

sure I'll give it a try. Will 26.02 be available on LVFS for the StarBook MkVIr2-Intel too ? It seems not even to be in lvfs-testing

**Comment by Sean-StarLabs** [comment]
Yup - should get it signed tomorrow

**Comment by divico** [comment]
It does indeed look much better on 26.02. At first glance, memory map inconsistencies are much less frequent. Out of 10 hibernation attempts, it only failed once, whereas on 25.12 (and below) it was more like the opposite 9 failures for one success.
I will test this over the next few weeks. I'm quite a frequent user of hibernate in many different scenarios. I'll try to identify a trigger.

**Comment by divico** [comment]
Connecting and disconnecting peripherals while the system is hibernated is definitely a trigger. E.g. connect docking station, hibernate, disconnect docking station and the resume will fail due to memory map change.

Still checking whether it also happens under some conditions with no peripherals connected.

**Comment by Sean-StarLabs** [comment]
TBT dock? Or just USB?

**Comment by divico** [comment]
> TBT dock? Or just USB?

Did not try USB only yet. It happens with a Dell WD19TB with screen (DP), USB keyboard and mouse connected, respectively disconnected. Will try to narrow down

**Comment by stikonas** [comment]
On 26.02 it happened to me once with no peripherals connected and a few successful resumes so far. So definitely it is looking better even if not completely fixed.

**Comment by divico** [comment]
I think I've found a trigger.

1. Disconnect all peripherals
2. Switch off the machine (blue LED off).
3. Switch on, boot the OS and hibernate.
4. While in S4 (blue LED off), connect a USB peripheral. I tested a USB flash drive, a Nitrokey 3A and a USB mouse in both the USB-A 3 and 2 ports. A microSD card in the built-in reader also triggers it.
5. Switching on and resuming from S4 will fail due to a memory map inconsistency.

Interestingly, this only occurs if the machine 'sees' the peripheral for the first time while in S4. If you disconnect the peripheral while the machine is on, then hibernate to S4, reconnect the peripheral and then resume, it will work. Steps 1 and 2 are therefore critical for triggering it.

There may be other ways to trigger it, of course, but this is what I've found so far. 

Can anyone replicate?

**Comment by divico** [comment]
@Sean-StarLabs   Is it technically possible to fix this?  I was thinking to Bounty finance someone to dedicate some efforts to get this fixed soon, but I have no idea whether it would help. Any thoughts?

**Comment by Sean-StarLabs** [comment]
Can you still see it in 26.04?

> Any thoughts?

Well, given we're ahead of everyone else in fixing, I doubt anyone else can help - save throwing a tonne of money at it, most of that going into them playing catch up.

**Comment by divico** [comment]
I see, thanks

> Can you still see it in 26.04?

I haven't tested it yet as I haven't identified anything relevant in the changelog, but since you think it's worth trying, I'll upgrade and report back in this issue

**Comment by divico** [comment]
> Can you still see it in 26.04?

Yes, very same issue on 26.04

**Comment by Sean-StarLabs** [comment]
Fixed with https://review.coreboot.org/c/coreboot/+/92554/3

**Comment by divico** [comment]
It this supposed to be fixed in `26.06` ?

On my Starbook MkVIr2-Intel it is not the case. Reproducing is as simple as connecting a USB device while hibernated.

**Comment by Sean-StarLabs** [comment]
Yuppo - can't replicate under any condition here, so debug build:

[starbook_rpl.zip](https://github.com/user-attachments/files/28699486/starbook_rpl.zip)

Install with `fwupdtool install-blob starbook_rpl.cap`

Then, make it break, then run:
```
wget -O /tmp/cbmem https://raw.githubusercontent.com/StarLabsLtd/firmware/refs/heads/26.06/binaries/cbmem && chmod +x /tmp/cbmem && sudo /tmp/cbmem -1 > cbmem.txt
```

And post that please

**Comment by divico** [comment]
> Then, make it break, then run:

Do you mean to trigger a failed resume from hibernation?

**Comment by Sean-StarLabs** [comment]
Yup

**Comment by divico** [comment]
here you go

[clean_boot.txt](https://github.com/user-attachments/files/29261738/clean_boot.txt)
[hibernate_failed.txt](https://github.com/user-attachments/files/29261739/hibernate_failed.txt)

is it helpful?

**Comment by Sean-StarLabs** [comment]
> is it helpful?

Very, thank you. Does that occur every time, or seemingly intermittent?

**Comment by divico** [comment]
> > is it helpful?
> 
> Very, thank you. Does that occur every time, or seemingly intermittent?

Resuming works reliably if no peripherals are connected.

Resuming fails quite systematically if a USB peripheral is connected while hibernated.  I can reproduce it systematically by simply connecting a USB mouse while hibernated.

There are less clear situations when a USB-C charger is connected/disconnected, it does sometimes still resume successfully.

**Comment by Sean-StarLabs** [comment]
Added MTI support in 26.07; if that doesn't do it, then going to need to debug with your specific devices, as I've tried every single thing we have here and they're all fine!

**Comment by divico** [comment]
@sim31 @r-vdp @stikonas  does resuming from hibernation work for you on `26.06` ?

**Comment by r-vdp** [comment]
> @sim31 @r-vdp @stikonas  does resuming from hibernation work for you on `26.06` ?

I have since upgraded to another laptop and my starbook is now acting as a CI runner, so I don't hibernate it anymore.

**Comment by divico** [comment]
> Added MTI support in 26.07

What is MTI ? Memory training?

**Comment by Sean-StarLabs** [comment]
Memory Type Information - backs up map, chucks it in DRAM on restore

**Comment by stikonas** [comment]
> [@sim31](https://github.com/sim31) [@r-vdp](https://github.com/r-vdp) [@stikonas](https://github.com/stikonas) does resuming from hibernation work for you on `26.06` ?

~Don't know. My Starbook MkVI is still on 26.02 and doesn't seem to have updates.~
so far 3 successful hibernations but will keep monitoring.

**Comment by divico** [comment]
> > [@sim31](https://github.com/sim31) [@r-vdp](https://github.com/r-vdp) [@stikonas](https://github.com/stikonas) does resuming from hibernation work for you on `26.06` ?
> 
> Don't know. My Starbook MkVI is still on 26.02 and doesn't seem to have updates.

Updates are available on LVFS, see here https://fwupd.org/lvfs/devices/com.starlabs.starbook.rpl

However you will never get updates while on 26.02. You must do a manual update to at least 26.05 to get new updates. This is because  fwupd now uses UEFI capsule to apply firmware updates. Read this https://support.starlabs.systems/hc/star-labs/articles/updating-your-firmware#manual-update

**Comment by divico** [comment]
> Added MTI support in 26.07; if that doesn't do it, then going to need to debug with your specific devices, as I've tried every single thing we have here and they're all fine!

seems to be fixed in 26.07 ! No single failed resume so far. Will test this heavily over next week and report back. Thanks

**Comment by sim31** [comment]
> [@sim31](https://github.com/sim31) [@r-vdp](https://github.com/r-vdp) [@stikonas](https://github.com/stikonas) does resuming from hibernation work for you on `26.06` ?

I'm still on 26.02 as well and now I'm reluctant to update because of this: https://github.com/StarLabsLtd/firmware/issues/440

**Comment by divico** [comment]
From my side, this issue is resolved.  Over the last five days, I have used hibernate or suspend-then-hibernate extensively ( ~30-40 times) with different peripherals connected and disconnected, and not a single resume has failed so far.
For me `26.07` is the first release that runs without any issues on my MkVIr2-Intel. Quite a milestone 👍
