### ISSUE TITLE
Question about long time support

### ISSUE THREAD

**Issue by fch02** [StarLabsLtd/firmware#82]
Hello, I was wondering about the 5 years support of updates offered by starlabs, does it mean it will always be limited by the starlabs team to develop and update it? No pull requestes permitted?
Does it mean that after 5 years, I need to buy a new labtop in order to have a coreboot updated?

**Comment by Sean-StarLabs** [comment]
It means we'll provide 5 years of updates to coreboot. Anyone can to submit a patch on Gerrit, or build their own version.

**Comment by fch02** [comment]
I see thanks for the info
