### ISSUE TITLE
Coreboot 8.32

### ISSUE THREAD

**Issue by autry7** [StarLabsLtd/firmware#86]
The coreboot update made my WD Black 850X disappear again. I was able to downgrade to 8.31 and am back up running. Just passing you the info.

**Comment by Sean-StarLabs** [comment]
Will restore the workaround. It'll be worth reporting it to WD - if you say it doesn't respond in time with FSP 3385, well, they'll probably ignore it, but it's worth a try!

**Comment by autry7** [comment]
They probably will ignore it. but I'll give that a shot. Thanks!

**Comment by autry7** [comment]
I know it's well after we talked about it, but I did send them an email.  Now we wait
