### ISSUE TITLE
[StarBook Mk VI - Intel - Coreboot] Attempting to build latest image of Coreboot firmware fails.

### ISSUE THREAD

**Issue by Hacksawfred3232** [StarLabsLtd/firmware#88]
While attempting to build the latest version of Coreboot, I get the following error from Make.
`make: *** No rule to make target '../intel-fsp/Adl.fd', needed by 'build/Fsp_M.fd'.  Stop.`
This is using the starlabs_starbook_adl config. Any idea what's going on?

**Comment by Sean-StarLabs** [comment]
That's the custom build of FSP I used for the last build - just comment these lines from the config file and it'll pull FSP from git:
```
CONFIG_FSP_FULL_FD=y
CONFIG_FSP_USE_REPO=n
CONFIG_FSP_FD_PATH="../intel-fsp/Adl.fd"
CONFIG_ADD_FSP_BINARIES=y
```
