### ISSUE TITLE
[StarBook MK VI - Intel - Coreboot] ITE 1.04 still with charging issues

### ISSUE THREAD

**Issue by cichy1173** [StarLabsLtd/firmware#90]
Hi. I have Coreboot 8.33 with ITE 1.04. After a week of using ITE 1.03 (and one day of using ITE 1.04) I have a problem with charging. Laptops charging LED is red, but Operating System does not recognize charging. I talked with Star Labs Team, and They are sure, that this is known charging issue in new ITE.

So I want to downgrade to Coreboot 8.31 (last stable) and ITE 1.01, but there is a problem - downgrading needs charging, but I need to downgrade to have charging (xD). How can I perform this downgrade being safe?

(this issue can be a follow up to #89 )

**Comment by Sean-StarLabs** [comment]
> downgrading needs charging

It only needs the AC connected, doesn't need the battery to be charging. Is your battery under 30%? If so, downgrade the EC with the EFI shell

**Comment by cichy1173** [comment]
> > downgrading needs charging
> 
> It only needs the AC connected, doesn't need the battery to be charging. Is your battery under 30%? If so, downgrade the EC with the EFI shell

I have output in terminal: 

> Nie można obecnie zaktualizować urządzenia StarBook (bios): Device requires AC power to be connected

First sentence in polish means "The StarBook device (bios) cannot currently be updated:"

**Comment by Sean-StarLabs** [comment]
That from fwupd? If so, I doubt they'll let us change it - even if it should be!

**Comment by cichy1173** [comment]
> That from fwupd? If so, I doubt they'll let us change it - even if it should be!

Yes, from Fwupd. I have only one idea - change maximum charging level to 60% (I have about 70% battery left) and then try to flash coreboot. Is it safe?

**Comment by cichy1173** [comment]
> downgrade the EC with the EFI shell

Ok, It is working, and charging is functional. 

Oh my God, ITE versions 1.03 and 1.04 are great - I am talking especially about touchpad and fan. 1.01 feels like I am using different laptop. 

I am waiting for stable release! Cheers!
