### ISSUE TITLE
Starbook MK V: Excessive Power Draw from USB-C Display

### ISSUE THREAD

**Issue by stan-janssen** [StarLabsLtd/firmware#93]
When I connect my StarBook MK V to a Dell S2719DC over USB-C, the monitor shuts down the connection with an "Excessive Power Draw from connected device" warning. The monitor is capable of delivering 45W PD, and I think the laptop want to draw 65W. 

My other laptop, a Thinkpad T15, works fine with this display.

Could it be that the Starbook does not take into account the maximum power delivery from the USB-C power source? Would it be possible to include this functionality? 

At the moment, I cannot use this display with this laptop when the laptop is not connected to its own power brick over the barrel jack.

**Comment by Sean-StarLabs** [comment]
Which variant and firmware versions?

**Comment by stan-janssen** [comment]
This is the Intel i7 variant with firmware version 8.15.

**Comment by stan-janssen** [comment]
```
$ cat /sys/class/dmi/id/ec_firmware_release
1.3
```

**Comment by stan-janssen** [comment]
Yes, that seems to work! Thanks.

It does require rebooting though (at least, that is what the Coreboot application tells me); is there something that can be done to auto-detect the max power from the power source and adjust the laptop's power draw accordingly?

**Comment by Sean-StarLabs** [comment]
Not in coreboot; AMI can

**Comment by stan-janssen** [comment]
Is this something that I should report to the Coreboot developers or is that not helpful?

https://ticket.coreboot.org/projects/coreboot
