### ISSUE TITLE
[Starbook MKVI AMD - AMI] Support USB-C displays for the bios?

### ISSUE THREAD

**Issue by garybowers** [StarLabsLtd/firmware#94]
Feature Request: BIOS Support for connected usb-c displays when in clamshell mode, allowing the configuration of the bios through connected displays and daisy chained peripherals such as USB keyboards.

**Comment by Sean-StarLabs** [comment]
edk2 will show itself on any display it can detect - are you just after a way of starting it that isn't software?

**Comment by Sean-StarLabs** [comment]
Not sure what's wanted, will close for now but feel free to re-open with more details
