### ISSUE TITLE
[Starbook MkVI - Intel][ami] fingerprints not deleting from sensor

### ISSUE THREAD

**Issue by aaron-gh** [StarLabsLtd/firmware#97]
I attempted to set up fingerprint login:
On first enroll it completed with no problems, however it was not working consistently so I deleted the print with:
`fprintd-delete $USER`
When I tried to enroll again, I got:
activated/Fprint/Device/0
Enrolling right-index-finger finger.
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-retry-scan
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-unknown-error
In an attempt to reproduce this issue, I added my left index finger, and then removed it and got the same after trying to perform a second enroll.
When I first set up the fingerprint sensor, I was running ITE1.01 and did not seem to have this issue. I am currently on 1.10 with ami 1.3.0

**Comment by Sean-StarLabs** [comment]
It's not firmware related, please ping support
